### ISSUE TITLE
Why E012 is an error when there is a css selection for columns?

### ISSUE THREAD

**Issue by miguelmich** [twbs/bootlint#389]
Hello,

In input-groups.less there is the following selection:

```less
.input-group {

  // Undo padding and float of grid classes
  &[class*="col-"] {
    float: none;
    padding-left: 0;
    padding-right: 0;
  }
}
```

Why do E012 is an error when you have an specific selection of the wrong way to use the markup?
